name: Add firmware links to pull request

on:
  workflow_run:
    workflows: [Firmware pull request validation]
    types: [completed]

jobs:
  add-artifact-links:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Get artifacts and generate comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run_id = context.payload.workflow_run.id;  // 실행 ID 가져오기
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run_id
            });
            
            let body = "Firmware for this pull request:\n";
            artifacts.data.artifacts.forEach(artifact => {
              body += `- [${artifact.name}](${artifact.archive_download_url})\n`;
            });
            
            // PR이 연결되어 있는지 확인
            if (context.payload.workflow_run.pull_requests.length > 0) {
              const issue_number = context.payload.workflow_run.pull_requests[0].number;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: body
              });
            } else {
              console.log("No pull request associated with this workflow run.");
            }
